pub(super) fn is_big_operator(name: &str) -> bool {
    matches!(
        name,
        "sum"
            | "prod"
            | "coprod"
            | "int"
            | "iint"
            | "iiint"
            | "iiiint"
            | "oint"
            | "oiint"
            | "oiiint"
            | "bigcup"
            | "bigcap"
            | "bigvee"
            | "bigwedge"
            | "bigoplus"
            | "bigotimes"
            | "bigodot"
            | "biguplus"
            | "bigsqcup"
            | "lim"
            | "liminf"
            | "limsup"
            | "min"
            | "max"
            | "sup"
            | "inf"
            | "argmin"
            | "argmax"
    )
}

pub(super) fn is_math_operator(name: &str) -> bool {
    matches!(
        name,
        "cos"
            | "sin"
            | "tan"
            | "cot"
            | "sec"
            | "csc"
            | "arccos"
            | "arcsin"
            | "arctan"
            | "arccot"
            | "arcsec"
            | "arccsc"
            | "cosh"
            | "sinh"
            | "tanh"
            | "coth"
            | "sech"
            | "csch"
            | "exp"
            | "log"
            | "ln"
            | "lg"
            | "max"
            | "min"
            | "sup"
            | "inf"
            | "lim"
            | "liminf"
            | "limsup"
            | "det"
            | "dim"
            | "arg"
            | "ker"
            | "gcd"
            | "lcm"
            | "Pr"
            | "deg"
            | "hom"
            | "mod"
            | "bmod"
            | "pmod"
            | "sinc"
            | "erf"
            | "tr"
            | "rank"
    )
}
