#![allow(clippy::needless_pass_by_value)]

//! On-device SLM cell summaries — opt-in, best-effort labels for the cell
//! picker, generated by Apple's FoundationModels via a vendored Swift
//! helper (`tools/nothelix-slm/main.swift`). Never on the picker's
//! critical path: refresh runs on a plain `std::thread` and reads are
//! cache-file lookups keyed by `djb2(cell text)` under
//! `~/.local/share/nothelix/summaries/<workspace>/<hash>`. Any failure —
//! no swiftc, no Apple Intelligence, a crashed helper — degrades silently
//! to "no summary", never an error surfaced to the editor.

use std::fs;
use std::io::{Read as _, Write as _};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, ExitStatus, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Mutex, OnceLock};
use std::time::{Duration, Instant};

const CELL_SEP: char = '\u{1e}';
const COMMAND_LINE_TOOLS_SDKS: &str = "/Library/Developer/CommandLineTools/SDKs";
const HELPER_TIMEOUT: Duration = Duration::from_secs(120);
const HELPER_POLL_INTERVAL: Duration = Duration::from_millis(50);

fn home_dir() -> PathBuf {
    std::env::var("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/tmp"))
}

fn helper_dir() -> PathBuf {
    home_dir().join(".local/share/nothelix/bin")
}

fn helper_path() -> PathBuf {
    helper_dir().join("nothelix-slm")
}

fn summaries_root() -> PathBuf {
    home_dir().join(".local/share/nothelix/summaries")
}

fn sanitize(key: &str) -> String {
    key.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// djb2 string hash — MUST match `djb2-hash` in
/// `plugin/nothelix/image-cache.scm` exactly: `h = h*33 + code`, modulo
/// `2147483647`, walked over Unicode scalar values (chars), not bytes.
fn djb2_hash(s: &str) -> i64 {
    let mut h: i64 = 5381;
    for c in s.chars() {
        h = (h * 33 + i64::from(c as u32)) % 2_147_483_647;
    }
    h
}

fn summary_path(root: &Path, workspace: &str, hash: &str) -> PathBuf {
    root.join(sanitize(workspace)).join(sanitize(hash))
}

fn cache_get(root: &Path, workspace: &str, hash: &str) -> String {
    fs::read_to_string(summary_path(root, workspace, hash)).unwrap_or_default()
}

fn cache_put(root: &Path, workspace: &str, hash: &str, content: &str) -> Result<(), String> {
    let path = summary_path(root, workspace, hash);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("ERROR: cannot create {}: {e}", parent.display()))?;
    }
    fs::write(&path, content).map_err(|e| format!("ERROR: cannot write {}: {e}", path.display()))
}

fn split_cells(blob: &str) -> Vec<&str> {
    blob.split(CELL_SEP).collect()
}

fn missing_hashes<'a>(root: &Path, workspace: &str, cells: &[&'a str]) -> Vec<&'a str> {
    cells
        .iter()
        .copied()
        .filter(|cell| !summary_path(root, workspace, &djb2_hash(cell).to_string()).exists())
        .collect()
}

fn sdk_name(path: &Path) -> Option<&str> {
    let name = path.file_name()?.to_str()?;
    if name.starts_with("MacOSX") && name.ends_with(".sdk") {
        Some(name)
    } else {
        None
    }
}

/// The lexicographically newest `MacOSX*.sdk` entry in `dir` — for the
/// real CommandLineTools layout this is the unversioned `MacOSXNN.sdk`
/// symlink (its trailing `s` in `.sdk` sorts after any dotted point
/// release's digit), which is exactly the "current" SDK for that major.
fn newest_sdk_in(dir: &Path) -> Option<PathBuf> {
    fs::read_dir(dir)
        .ok()?
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| sdk_name(path).is_some())
        .max_by(|a, b| sdk_name(a).cmp(&sdk_name(b)))
}

fn try_plain_swiftc(source: &Path, out: &Path) -> bool {
    Command::new("swiftc")
        .arg(source)
        .arg("-o")
        .arg(out)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

fn try_fallback_swiftc(source: &Path, out: &Path, sdk: &Path) -> bool {
    Command::new("swiftc")
        .env("DEVELOPER_DIR", "/Library/Developer/CommandLineTools")
        .arg("-sdk")
        .arg(sdk)
        .arg(source)
        .arg("-o")
        .arg(out)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

fn compile_helper(source: &Path, out: &Path) -> bool {
    if try_plain_swiftc(source, out) && out.exists() {
        return true;
    }
    match newest_sdk_in(Path::new(COMMAND_LINE_TOOLS_SDKS)) {
        Some(sdk) => try_fallback_swiftc(source, out, &sdk) && out.exists(),
        None => false,
    }
}

/// Ensure the compiled helper binary exists, compiling it from the
/// embedded vendored source on first use. Existence alone is the cache
/// check — the source is vendored in this binary, so it never goes
/// stale under a running process.
fn ensure_helper() -> bool {
    let path = helper_path();
    if path.exists() {
        return true;
    }
    let Some(dir) = path.parent() else {
        return false;
    };
    if fs::create_dir_all(dir).is_err() {
        return false;
    }
    let Ok(tmp) = tempfile::Builder::new().suffix(".swift").tempfile() else {
        return false;
    };
    let source = include_str!("../../tools/nothelix-slm/main.swift");
    if fs::write(tmp.path(), source).is_err() {
        return false;
    }
    compile_helper(tmp.path(), &path)
}

fn probe_available() -> bool {
    Command::new(helper_path())
        .arg("--probe")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

/// Waits for `child` to exit, polling `try_wait` so a `timeout` can be
/// enforced without blocking forever on a wedged helper. Kills and reaps
/// the child on expiry. `stdout` is drained concurrently on a reader
/// thread so a full pipe buffer can't deadlock the wait loop.
fn wait_with_timeout(mut child: Child, timeout: Duration) -> Option<(ExitStatus, String)> {
    let mut stdout = child.stdout.take()?;
    let reader = std::thread::spawn(move || {
        let mut buf = String::new();
        let _ = stdout.read_to_string(&mut buf);
        buf
    });
    let deadline = Instant::now() + timeout;
    loop {
        match child.try_wait() {
            Ok(Some(status)) => {
                let out = reader.join().unwrap_or_default();
                return Some((status, out));
            }
            Ok(None) => {
                if Instant::now() >= deadline {
                    let _ = child.kill();
                    let _ = child.wait();
                    let _ = reader.join();
                    return None;
                }
                std::thread::sleep(HELPER_POLL_INTERVAL);
            }
            Err(_) => return None,
        }
    }
}

fn run_helper(path: &Path, stdin_blob: &str) -> Option<String> {
    run_helper_with_timeout(path, stdin_blob, HELPER_TIMEOUT)
}

fn run_helper_with_timeout(path: &Path, stdin_blob: &str, timeout: Duration) -> Option<String> {
    let mut child = Command::new(path)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    child.stdin.take()?.write_all(stdin_blob.as_bytes()).ok()?;
    let (status, stdout) = wait_with_timeout(child, timeout)?;
    if !status.success() {
        return None;
    }
    Some(stdout)
}

/// A cell whose text carries nothing to summarize — never sent to the
/// helper, its cache file is pre-seeded with an empty label instead.
fn is_blank_cell(cell: &str) -> bool {
    cell.trim().is_empty()
}

/// Splits `misses` into (blank, non-blank) so callers can seed blanks
/// locally and send only non-blank cells to the helper — Swift's
/// `omittingEmptySubsequences: true` drops empty stdin fields, which
/// would otherwise shift a positional zip of the helper's stdout lines
/// against the original miss list.
fn partition_misses<'a>(misses: &[&'a str]) -> (Vec<&'a str>, Vec<&'a str>) {
    misses.iter().copied().partition(|cell| is_blank_cell(cell))
}

fn seed_blank_cells(root: &Path, workspace: &str, blanks: &[&str]) {
    for cell in blanks {
        let hash = djb2_hash(cell).to_string();
        let _ = cache_put(root, workspace, &hash, "");
    }
}

/// Assigns each line of the helper's stdout to the non-blank cell at the
/// same position — sound only because `non_blanks` is exactly what was
/// sent to the helper (blanks already filtered out by `partition_misses`).
fn assign_responses(root: &Path, workspace: &str, non_blanks: &[&str], stdout: &str) {
    for (cell, line) in non_blanks.iter().zip(stdout.lines()) {
        let hash = djb2_hash(cell).to_string();
        let _ = cache_put(root, workspace, &hash, line);
    }
}

fn refresh_worker(root: &Path, workspace: &str, cells_blob: &str) {
    if !ensure_helper() {
        return;
    }
    let cells = split_cells(cells_blob);
    let misses = missing_hashes(root, workspace, &cells);
    if misses.is_empty() {
        return;
    }
    let (blanks, non_blanks) = partition_misses(&misses);
    seed_blank_cells(root, workspace, &blanks);
    if non_blanks.is_empty() {
        return;
    }
    let stdin_blob = non_blanks.join(&CELL_SEP.to_string());
    let Some(stdout) = run_helper(&helper_path(), &stdin_blob) else {
        return;
    };
    assign_responses(root, workspace, &non_blanks, &stdout);
}

static SLM_AVAILABLE: OnceLock<Mutex<Option<bool>>> = OnceLock::new();

/// "yes"/"no" — helper compiled (or already present) AND `--probe` exits
/// 0. Memoized for the process lifetime; never errors, any failure along
/// the way collapses to "no".
pub fn slm_available(_workspace: String) -> String {
    let lock = SLM_AVAILABLE.get_or_init(|| Mutex::new(None));
    let mut guard = lock.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
    let available = *guard.get_or_insert_with(|| ensure_helper() && probe_available());
    if available { "yes".into() } else { "no".into() }
}

static REFRESH_IN_FLIGHT: AtomicBool = AtomicBool::new(false);

/// Claims the process-global refresh slot; `false` means a refresh is
/// already running and the caller must not spawn another one.
fn try_acquire_in_flight() -> bool {
    REFRESH_IN_FLIGHT
        .compare_exchange(false, true, Ordering::SeqCst, Ordering::SeqCst)
        .is_ok()
}

fn release_in_flight() {
    REFRESH_IN_FLIGHT.store(false, Ordering::SeqCst);
}

/// Releases the in-flight slot on drop, including on an unwind out of the
/// worker thread, so a panicking refresh can't wedge every future call.
struct InFlightGuard;

impl Drop for InFlightGuard {
    fn drop(&mut self) {
        release_in_flight();
    }
}

/// Fire-and-forget background refresh: returns "" immediately, spawns a
/// plain `std::thread` (never `spawn-native-thread` — see
/// `reference_steel_native_thread_freeze.md`) that batches every cell
/// text in `cells_blob` (`\x1e`-separated) whose hash has no cache file
/// yet through ONE helper process invocation. A process-global in-flight
/// flag makes repeated calls (e.g. every picker open) a no-op while a
/// batch is already running, so a slow or wedged helper can't pile up
/// unbounded subprocesses.
pub fn slm_refresh_summaries(workspace: String, cells_blob: String) -> String {
    if !try_acquire_in_flight() {
        return String::new();
    }
    std::thread::spawn(move || {
        let _guard = InFlightGuard;
        refresh_worker(&summaries_root(), &workspace, &cells_blob);
    });
    String::new()
}

/// Cached SLM label for `hash` under `workspace`, "" on a cache miss
/// (never queried yet, or the background refresh hasn't caught up).
pub fn slm_summary_for(workspace: String, hash: String) -> String {
    cache_get(&summaries_root(), &workspace, &hash)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    /// Reference value is `(djb2-hash "abc")` evaluated with `steel`
    /// against the exact definition in `plugin/nothelix/image-cache.scm`.
    #[test]
    fn djb2_matches_scheme_reference_value() {
        assert_eq!(djb2_hash("abc"), 193_485_963);
    }

    #[test]
    fn djb2_of_empty_string_is_seed() {
        assert_eq!(djb2_hash(""), 5381);
    }

    #[test]
    fn djb2_hashes_unicode_by_scalar_value_not_byte() {
        let ascii = djb2_hash("a");
        let multibyte = djb2_hash("\u{2200}");
        assert_ne!(ascii, multibyte);
        assert_eq!(multibyte, 5381_i64 * 33 + 0x2200);
    }

    #[test]
    fn cache_roundtrip() {
        let root = tempdir().unwrap();
        assert_eq!(cache_get(root.path(), "ws", "42"), "");
        cache_put(root.path(), "ws", "42", "null space basis").unwrap();
        assert_eq!(cache_get(root.path(), "ws", "42"), "null space basis");
    }

    #[test]
    fn cache_write_empty_line_still_lands_a_file() {
        let root = tempdir().unwrap();
        cache_put(root.path(), "ws", "1", "").unwrap();
        assert!(summary_path(root.path(), "ws", "1").exists());
        assert_eq!(cache_get(root.path(), "ws", "1"), "");
    }

    #[test]
    fn distinct_workspaces_isolate() {
        let root = tempdir().unwrap();
        cache_put(root.path(), "wsA", "1", "a-label").unwrap();
        cache_put(root.path(), "wsB", "1", "b-label").unwrap();
        assert_eq!(cache_get(root.path(), "wsA", "1"), "a-label");
        assert_eq!(cache_get(root.path(), "wsB", "1"), "b-label");
    }

    #[test]
    fn sanitizes_path_separators_in_workspace() {
        let root = tempdir().unwrap();
        cache_put(root.path(), "/abs/ws/../x", "1", "v").unwrap();
        assert_eq!(cache_get(root.path(), "/abs/ws/../x", "1"), "v");
    }

    #[test]
    fn split_cells_on_record_separator() {
        let blob = format!("first{CELL_SEP}second{CELL_SEP}third");
        assert_eq!(split_cells(&blob), vec!["first", "second", "third"]);
    }

    #[test]
    fn split_cells_single_entry_has_no_separator() {
        assert_eq!(split_cells("only"), vec!["only"]);
    }

    #[test]
    fn missing_hashes_skips_cells_with_a_cache_file() {
        let root = tempdir().unwrap();
        let hash_of_a = djb2_hash("cell a").to_string();
        cache_put(root.path(), "ws", &hash_of_a, "already cached").unwrap();
        let cells = ["cell a", "cell b"];
        assert_eq!(missing_hashes(root.path(), "ws", &cells), vec!["cell b"]);
    }

    #[test]
    fn missing_hashes_empty_when_all_cached() {
        let root = tempdir().unwrap();
        let cells = ["x", "y"];
        for cell in cells {
            cache_put(root.path(), "ws", &djb2_hash(cell).to_string(), "l").unwrap();
        }
        assert!(missing_hashes(root.path(), "ws", &cells).is_empty());
    }

    #[test]
    fn newest_sdk_picks_the_unversioned_major_symlink() {
        let dir = tempdir().unwrap();
        for name in [
            "MacOSX15.sdk",
            "MacOSX26.sdk",
            "MacOSX26.5.sdk",
            "MacOSX27.0.sdk",
            "MacOSX27.sdk",
            "MacOSX.sdk",
        ] {
            fs::write(dir.path().join(name), b"").unwrap();
        }
        let picked = newest_sdk_in(dir.path()).unwrap();
        assert_eq!(
            picked.file_name().unwrap().to_str().unwrap(),
            "MacOSX27.sdk"
        );
    }

    #[test]
    fn newest_sdk_ignores_non_sdk_entries() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("readme.txt"), b"").unwrap();
        assert!(newest_sdk_in(dir.path()).is_none());
    }

    #[test]
    fn newest_sdk_missing_dir_is_none() {
        let dir = tempdir().unwrap();
        assert!(newest_sdk_in(&dir.path().join("does-not-exist")).is_none());
    }

    #[test]
    fn partition_misses_separates_blank_from_non_blank() {
        let misses = ["print(1)", "", "print(2)", "   "];
        let (blanks, non_blanks) = partition_misses(&misses);
        assert_eq!(blanks, vec!["", "   "]);
        assert_eq!(non_blanks, vec!["print(1)", "print(2)"]);
    }

    /// Reproduces the batch mislabeling bug: an empty cell in the middle
    /// of the miss list must not shift the helper's stdout lines onto
    /// the wrong hashes. `partition_misses` pulls the empty cell out
    /// before the blob is built, `seed_blank_cells` caches it directly,
    /// and `assign_responses` zips the stub "helper stdout" only against
    /// the non-blank cells that were actually sent.
    #[test]
    fn empty_cell_in_batch_does_not_shift_neighboring_hashes() {
        let root = tempdir().unwrap();
        let cells = ["print(1)", "", "print(2)"];
        let misses = missing_hashes(root.path(), "ws", &cells);
        assert_eq!(misses, vec!["print(1)", "", "print(2)"]);

        let (blanks, non_blanks) = partition_misses(&misses);
        seed_blank_cells(root.path(), "ws", &blanks);

        let stub_helper_stdout = "prints one\nprints two\n";
        assign_responses(root.path(), "ws", &non_blanks, stub_helper_stdout);

        assert_eq!(
            cache_get(root.path(), "ws", &djb2_hash("print(1)").to_string()),
            "prints one"
        );
        assert_eq!(
            cache_get(root.path(), "ws", &djb2_hash("print(2)").to_string()),
            "prints two"
        );
        assert_eq!(cache_get(root.path(), "ws", &djb2_hash("").to_string()), "");
    }

    #[test]
    fn seed_blank_cells_writes_empty_label_without_calling_helper() {
        let root = tempdir().unwrap();
        seed_blank_cells(root.path(), "ws", &["", "   "]);
        assert_eq!(cache_get(root.path(), "ws", &djb2_hash("").to_string()), "");
        assert_eq!(
            cache_get(root.path(), "ws", &djb2_hash("   ").to_string()),
            ""
        );
    }

    #[test]
    fn in_flight_guard_blocks_second_acquire_until_released() {
        release_in_flight();
        assert!(try_acquire_in_flight());
        assert!(!try_acquire_in_flight());
        release_in_flight();
        assert!(try_acquire_in_flight());
        release_in_flight();
    }

    #[test]
    fn in_flight_guard_releases_on_drop_even_after_panic() {
        release_in_flight();
        assert!(try_acquire_in_flight());
        let result = std::panic::catch_unwind(|| {
            let _guard = InFlightGuard;
            panic!("simulated worker panic");
        });
        assert!(result.is_err());
        assert!(try_acquire_in_flight());
        release_in_flight();
    }

    /// The fixture uses `exec sleep 5` rather than a bare `sleep 5` so the
    /// shell replaces itself in place instead of forking `sleep` as a
    /// child — killing the spawned process then closes its stdout pipe
    /// immediately, instead of leaving an orphaned grandchild holding the
    /// write end open until its own sleep elapses.
    #[test]
    fn run_helper_kills_and_returns_none_on_timeout() {
        let dir = tempdir().unwrap();
        let script = dir.path().join("hang.sh");
        fs::write(&script, "#!/bin/sh\nexec sleep 5\n").unwrap();
        {
            use std::os::unix::fs::PermissionsExt as _;
            let mut perms = fs::metadata(&script).unwrap().permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&script, perms).unwrap();
        }

        let started = Instant::now();
        let result = run_helper_with_timeout(&script, "input", Duration::from_millis(150));
        assert!(result.is_none());
        assert!(
            started.elapsed() < Duration::from_secs(2),
            "timeout should kill the wedged helper well before its 5s sleep completes"
        );
    }
}
